name: Fly Deploy
on:
  push:
    branches:
      - main  # Triggers the deploy every time you push to the 'main' branch

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --secrets GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
